name: build
run-name: >
  ${{ inputs.versions }}
  ${{ fromJSON('{"Pro":"PRO","Home":"HOME","Multi":"MULTI"}')[inputs.edition] }}
  ${{ fromJSON('{"x64":"X64","arm64":"ARM64"}')[inputs.architecture] }}
  ${{ fromJSON('{"ar-sa":"AR","bg-bg":"BG","cs-cz":"CS","da-dk":"DA","de-de":"DE","el-gr":"EL","en-gb":"EN","en-us":"EN","es-es":"ES","es-mx":"ES","et-ee":"ET","fi-fi":"FI","fr-ca":"FR","fr-fr":"FR","he-il":"HE","hr-hr":"HR","hu-hu":"HU","it-it":"IT","ja-jp":"JA","ko-kr":"KO","lt-lt":"LT","lv-lv":"LV","nb-no":"NB","nl-nl":"NL","pl-pl":"PL","pt-br":"PT","pt-pt":"PT","ro-ro":"RO","ru-ru":"RU","sk-sk":"SK","sl-si":"SL","sr-latn-rs":"SR","sv-se":"SV","th-th":"TH","tr-tr":"TR","uk-ua":"UK","zh-cn":"ZH","zh-tw":"ZH"}')[inputs.language] }}
  ${{ inputs.esd && 'ESD' || '' }}
  ${{ inputs.drivers && 'DRIVERS' || '' }}
  ${{ inputs.netfx3 && 'NETFX3' || '' }}
  
on:
  workflow_dispatch:
    inputs:
      architecture:
        description: "Windows architecture to build"
        type: choice
        options: [x64, arm64]
        default: x64
        required: true
      versions:
        description: "Windows version to build"
        type: choice
        options:
        - Windows 10 22H2
        - Windows 11 23H2
        - Windows 11 24H2
        - Windows 11 24H2 BETA
        - Windows 11 25H2 DEV
        - Windows 11 Canary
        default: Windows 11 24H2
        required: true
      edition:
        description: "Windows edition to build"
        type: choice
        options: [Pro, Home, Multi]
        default: Pro
        required: true
      language:
        description: "Language"
        type: choice
        options:
        - ar-sa
        - bg-bg
        - cs-cz
        - da-dk
        - de-de
        - el-gr
        - en-gb
        - en-us
        - es-es
        - es-mx
        - et-ee
        - fi-fi
        - fr-ca
        - fr-fr
        - he-il
        - hr-hr
        - hu-hu
        - it-it
        - ja-jp
        - ko-kr
        - lt-lt
        - lv-lv
        - nb-no
        - nl-nl
        - pl-pl
        - pt-br
        - pt-pt
        - ro-ro
        - ru-ru
        - sk-sk
        - sl-si
        - sr-latn-rs
        - sv-se
        - th-th
        - tr-tr
        - uk-ua
        - zh-cn
        - zh-tw
        default: en-us
        required: true
      esd:
        description: "Use ESD compression"
        type: boolean
        required: true
        default: false
      drivers:
        description: "Add additional drivers"
        type: boolean
        required: true
        default: false
      netfx3:
        description: "Add .NET Framework 3.5"
        type: boolean
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ${{ fromJSON('{"x64":"windows-2022","arm64":"windows-11-arm"}')[inputs.architecture] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init options
        shell: pwsh
        run: echo "options=" >> $env:GITHUB_ENV

      - name: Enable ESD
        if: ${{ inputs.esd }}
        shell: pwsh
        run: echo "options=$env:options -esd" >> $env:GITHUB_ENV

      - name: Enable additional drivers
        if: ${{ inputs.drivers }}
        shell: pwsh
        run: echo "options=$env:options -drivers" >> $env:GITHUB_ENV

      - name: Enable .NET Framework 3.5
        if: ${{ inputs.netfx3 }}
        shell: pwsh
        run: echo "options=$env:options -netfx3" >> $env:GITHUB_ENV

      - name: Build Windows
        id: build_windows
        shell: pwsh
        run: |
          pwsh uup-dump-get-windows-iso.ps1 ${{ (inputs.versions) == 'Windows 10 22H2' && ' windows-10 ' || (inputs.versions) == 'Windows 11 23H2' && ' windows-11old ' || (inputs.versions) == 'Windows 11 24H2' && ' windows-11 ' || (inputs.versions) == 'Windows 11 24H2 BETA' && ' windows-11beta ' || (inputs.versions) == 'Windows 11 25H2 DEV' && ' windows-11dev ' || (inputs.versions) == 'Windows 11 Canary' && ' windows-11canary ' }} c:/output -architecture ${{ inputs.architecture }} -edition ${{ inputs.edition }} -lang ${{ inputs.language }} ${{ env.options }}
          echo "iso_name=$env:ISO_NAME" >> $env:GITHUB_OUTPUT

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ISO_NAME }}
          path: c:/output/*.ISO
          if-no-files-found: error

      - name: Build summary
        id: build_summary
        shell: pwsh
        env:
          ARTIFACT_URL: ${{ steps.upload_artifact.outputs.artifact-url }}
        run: |
          $iso = Get-Content (Resolve-Path c:/output/*.json) | ConvertFrom-Json
          $imageNames = $iso.images | ForEach-Object { $_.name }
          if ($imageNames.Count -gt 1) {
            if ($imageNames[0] -match '^(Windows (10|11))\s*(.*)') {
              $prefix = $matches[1]
              $first = $imageNames[0]
              $rest = $imageNames[1..($imageNames.Count - 1)] | ForEach-Object { ($_ -replace "^$prefix\s*", '') }
              $finalImageName = $first + '/' + ($rest -join '/')
            } else {
              $finalImageName = $imageNames -join '/'
            }
          } else {
            $finalImageName = $imageNames
          }

          Add-Content $env:GITHUB_STEP_SUMMARY @"
          | Property | Value |
          | :--- | :--- |
          | Name | $finalImageName $($iso.version) |
          | Build | $($iso.build) |
          | Architecture | ${{ inputs.architecture }} |
          | Checksum | $($iso.checksum) |
          | Image Name | $finalImageName |
          | Iso | [$env:ISO_NAME]($env:ARTIFACT_URL) |
          | UUP dump | [$($iso.title)]($($iso.uupDump.downloadUrl)) |
          "@

          (Get-Content $env:GITHUB_STEP_SUMMARY) | Set-Content summary.md
          echo "build=$($iso.build)" >> $env:GITHUB_ENV
          echo "version=$($iso.version)" >> $env:GITHUB_ENV
          echo "name=$($iso.name)" >> $env:GITHUB_ENV
          echo "title=$($iso.title)" >> $env:GITHUB_ENV
          echo "images=$($finalImageName)" >> $env:GITHUB_ENV
          echo "tagname=$($iso.build).$($iso.version).${{ fromJSON('{"Pro":"PRO","Home":"HOME","Multi":"MULTI"}')[inputs.edition] }}.${{ fromJSON('{"x64":"X64","arm64":"ARM64"}')[inputs.architecture] }}.${{ fromJSON('{"ar-sa":"AR","bg-bg":"BG","cs-cz":"CS","da-dk":"DA","de-de":"DE","el-gr":"EL","en-gb":"EN","en-us":"EN","es-es":"ES","es-mx":"ES","et-ee":"ET","fi-fi":"FI","fr-ca":"FR","fr-fr":"FR","he-il":"HE","hr-hr":"HR","hu-hu":"HU","it-it":"IT","ja-jp":"JA","ko-kr":"KO","lt-lt":"LT","lv-lv":"LV","nb-no":"NB","nl-nl":"NL","pl-pl":"PL","pt-br":"PT","pt-pt":"PT","ro-ro":"RO","ru-ru":"RU","sk-sk":"SK","sl-si":"SL","sr-latn-rs":"SR","sv-se":"SV","th-th":"TH","tr-tr":"TR","uk-ua":"UK","zh-cn":"ZH","zh-tw":"ZH"}')[inputs.language] }} $($iso.tags)" >> $env:GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.tagname }}"
          name: "${{ env.images }} ${{ inputs.architecture}} ${{ env.version }} (${{ env.build }})"
          body_path: summary.md
          draft: false
          prerelease: false
