name: build
run-name: "Build ${{ inputs.versions }} ${{ inputs.edition }} ${{ inputs.language }} ${{ (inputs.esd) && 'ESD' || '' }} ${{ (inputs.drivers) && 'DRIVERS' || '' }} ${{ (inputs.netfx3) && 'NETFX3' || '' }}"

on:
  workflow_dispatch:
    inputs:
      versions:
        description: "Windows version to build"
        type: choice
        options:
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 10 22H2
        default: Windows 11 24H2
        required: true
      edition:
        description: "Windows edition to build"
        type: choice
        options:
        - Pro
        - Home
        - Multi
        default: Pro
        required: true
      language:
        description: "Language"
        type: choice
        options:
        - AR-SA
        - BG-BG
        - CS-CZ
        - DA-DK
        - DE-DE
        - EL-GR
        - EN-GB
        - EN-US
        - ES-ES
        - ES-MX
        - ET-EE
        - FI-FI
        - FR-CA
        - FR-FR
        - HE-IL
        - HR-HR
        - HU-HU
        - IT-IT
        - JA-JP
        - KO-KR
        - LT-LT
        - LV-LV
        - NB-NO
        - NL-NL
        - PL-PL
        - PT-BR
        - PT-PT
        - RO-RO
        - RU-RU
        - SK-SK
        - SL-SI
        - SR-LATN-RS
        - SV-SE
        - TH-TH
        - TR-TR
        - UK-UA
        - ZH-CN
        - ZH-TW
        default: EN-US
        required: true
      esd:
        description: "Use ESD compression"
        type: boolean
        required: true
        default: false
      drivers:
        description: "Add additional drivers"
        type: boolean
        required: true
        default: false
      netfx3:
        description: "Add .NET Framework 3.5"
        type: boolean
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log the available disk space, so we can inspect it later.
      # NB GitHub-hosted runners have limited available disk space.
      #    see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      - name: Show available disk space before build
        run: |
          Get-PSDrive -PSProvider FileSystem
          echo "options=" >> $env:GITHUB_ENV

      # NB we are writing outside of the current working/job directory
      #    because it does not have sufficient available disk space.
      - name: Enable ESD
        if: ${{ inputs.esd }}
        run: echo "options=${{ env.options }} -esd" >> $env:GITHUB_ENV

      - name: Enable additional drivers
        if: ${{ inputs.drivers }}
        run: echo "options=${{ env.options }} -drivers" >> $env:GITHUB_ENV

      - name: Enable .NET Framework 3.5
        if: ${{ inputs.netfx3 }}
        run: echo "options=${{ env.options }} -netfx3" >> $env:GITHUB_ENV

      - name: Build Windows 11 24H2
        if: ${{ inputs.versions == 'Windows 11 24H2' }}
        run: pwsh uup-dump-get-windows-iso.ps1 windows-11 c:/output -edition ${{ inputs.edition }} -lang ${{ inputs.language }} ${{ env.options }}

      - name: Build Windows 11 23H2
        if: ${{ inputs.versions == 'Windows 11 23H2' }}
        run: pwsh uup-dump-get-windows-iso.ps1 windows-11old c:/output -edition ${{ inputs.edition }} -lang ${{ inputs.language }} ${{ env.options }}

      - name: Build Windows 10 22H2
        if: ${{ inputs.versions == 'Windows 10 22H2' }}
        run: pwsh uup-dump-get-windows-iso.ps1 windows-10 c:/output -edition ${{ inputs.edition }} -lang ${{ inputs.language }} ${{ env.options }}

      - name: Show available disk space after build
        run: Get-PSDrive -PSProvider FileSystem

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        # env:
        #  ISO_NAME: ${{ steps.build.outputs.ISO_NAME }}
        with:
          name: ${{ env.ISO_NAME }}
          path: c:/output/*.ISO
          if-no-files-found: error 
      
      - name: Set artifact_url
        id: set_artifact_url
        run: echo "artifact_url=${{ steps.upload_artifact.outputs.artifact-url }}" >> $env:GITHUB_ENV
        
      - name: Build summary
        id: build_summary
        run: |
          $iso = Get-Content (Resolve-Path c:/output/*.json) | ConvertFrom-Json
          $imageNames = $iso.images | ForEach-Object { $_.name }
          if ($imageNames.Count -gt 1) {
            if ($imageNames[0] -match '^(Windows (10|11))\s*(.*)') {
              $prefix = $matches[1]
              $first = $imageNames[0]
              $rest = $imageNames[1..($imageNames.Count - 1)] | ForEach-Object { ($_ -replace "^$prefix\s*", '') }
              $finalImageName = $first + '/' + ($rest -join '/')
            } else {
              $finalImageName = $imageNames -join '/'
            }
          } else{
            $finalImageName = $imageNames
          } 

          Add-Content $env:GITHUB_STEP_SUMMARY @"
          | Property | Value |
          | :--- | :--- |
          | Name | $($finalImageName) ${{ env.version }} |
          | Build | $($iso.build) |
          | Checksum | $($iso.checksum) |
          | Image Name | $finalImageName |
          | Iso | [$env:ISO_NAME]($env:artifact_url) |
          | UUP dump | [$($iso.title)]($($iso.uupDump.downloadUrl)) |
          "@
          # Save the GITHUB_STEP_SUMMARY contents to a file
          (Get-Content $env:GITHUB_STEP_SUMMARY) | Set-Content summary.md
          echo "build=$($iso.build)" >> $env:GITHUB_ENV
          echo "version=$($iso.version)" >> $env:GITHUB_ENV
          echo "name=$($iso.name)" >> $env:GITHUB_ENV
          echo "title=$($iso.title)" >> $env:GITHUB_ENV
          echo "images=$($finalImageName)" >> $env:GITHUB_ENV
          echo "RUN_NAME=$($finalImageName) $($iso.version) ($($iso.build))" >> $GITHUB_ENV
          echo "tagname=v$($iso.build).$($iso.version).${{ inputs.language }}$($iso.tags)" >> $env:GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.tagname }}"
          name: "${{ env.images }} ${{ env.version }} (${{ env.build }})"
          body_path: summary.md
          draft: false
          prerelease: false
